# Generated by Django 6.0 on 2026-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_no',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
